### PR TITLE
Generate waveforms from math

### LINKED ISSUE #36: Generate waveform based on a math expression
It would be nice that if in addition to drawing a waveform ourselves, we could calculate it based on a math expression. Examples:

sin(t) would give a classic sinewave
wave(0)+wave(4)-wave(2) would add wave 0 and 4 together, then subtract wave 2 from it (using current wave's number there could lead to infinite loop and as such wouldn't be allowed)

Possibly even more fun stuff that I don't know would be possible. The idea came after playing around with LMMS Nightly Xpressive plugin that generates waveforms from equations.

### PR DESCRIPTION
**Pull request by Dannode36**
- Resolves #36 

As outlined in #36, this would allow users to generate waveforms from maths expressions similar to that of LMMS Nightly Xpressive and Fruity Formula Controller. This feature would be found in the wave editor and would allow for creation of static waveforms through mathematical operations.

- [x] Integrate NCalc library
- [x] Provide WaveTracker variables for use as inbuilt variables/constants in expressions
    - [x] "x": 'wave sample radian' where step 64 in the wave editor equals 2pi when evaluating
- [x] Modify WaveModifyDialog to allow for a specific width during creation
- [x] Integrate the parser into the wave editor UI
    - [x] Expression input
    - [x] Wavefolding option
    - [x] Expression compilation error messages
    - [x] "Real-time" variable controls. Something like Fruity Formula Controller with its a, b and c knob
        - ~~Some new UI element like a knob or a slider??? (Rotating sprites might be a little more difficult)~~

### CODE REVIEW

**Comment by Dannode36** [comment]
I think this is pretty much complete now. Can't really think of much else to add unless the UI isn't up to taste :p

**Comment by Dannode36** [comment]
If you'd like @squiggythings, I'm happy to make an PR on the [wavetracker-site](https://github.com/squiggythings/wavetracker-site) repo to provide some documentation on how to use this new dialog. If I was to do that, do you think adding a dedicated reference page is the way to go? (plus some documentation on the WaveBank page)

**Comment by squiggythings** [comment]
Great! I'll review it next chance I get. And no need to worry about the documentation, I will add that information when I update it for the rest of the additions in this update.

**Comment by squiggythings** [comment]
Looks good! It's a lot of fun to play around with and experiment!
I made a few small changes to further improve the UX: the expression box updates live as you are typing, and I switched out t/x to range from 0 to 1 across the wave duration, so instead the conversion from radians happens inside the sin and cosine functions. This way the input matches the other primitive wave functions I added, like saw(x), tri(x), square and pulse waves, and frees up t to be used for other time-based parts of the expression. For example a voice-like, formant kind of sound: "sin(5*x)*(1-t)"

**Comment by Dannode36** [comment]
Awesome! Ah I completely forgot to carry over the saw and triangle etc. functions so thanks for adding them back

**Pull request closed without merging**
