### PR TITLE
[FEATURE] Generate waveforms from math expressions

### LINKED ISSUE #36: Generate waveform based on a math expression
It would be nice that if in addition to drawing a waveform ourselves, we could calculate it based on a math expression. Examples:

sin(t) would give a classic sinewave
wave(0)+wave(4)-wave(2) would add wave 0 and 4 together, then subtract wave 2 from it (using current wave's number there could lead to infinite loop and as such wouldn't be allowed)

Possibly even more fun stuff that I don't know would be possible. The idea came after playing around with LMMS Nightly Xpressive plugin that generates waveforms from equations.

### PR DESCRIPTION
**Pull request by Dannode36**
## Description

As outlined in #36, this would allow users to generate waveforms from maths expressions similar to that of LMMS Nightly Xpressive and Fruity Formula Controller (doesn't actually produce audio). 

## Tasks
- [x] Integrate NCalc library
- [x] Provide WaveTracker variables for use as inbuilt variables/constants in expressions
    - [x] "x": wave sample radian where step 64 = 2pi
    - [ ] "t": time since song start
    - [ ] All functions from custom parser implementation (see commit history)
- [ ] Integrate the parser into the wave editor UI
    - [x] Expression input
    - [x] Wavefolding option
    - [x] Syntax/compilation error messages
    - [x] Math Instrument
    - [ ] Expression editor UI
- [x] Implement compilation of expression to lambdas (for super speedy evaluation)

### CODE REVIEW

**Comment by squiggythings** [comment]
Thanks for your contributions. Out of curiosity, how will the interface look/behave for this feature? I think it should open a dialog similar to how the "Modify..." dialogs behave, it might be better to rename that dropdown button to something like "More tools..." or "Advanced..." so that the Generate from expression can be put in there, as I wouldn't want something like this on the main wave editing window which in my opinion should be dedicated to just drawing and could confuse/overwhelm users who are unfamiliar with wavetable synthesis.

**Comment by Dannode36** [comment]
No problem at all! During my testing the expression input and generate button currently sit to the right of the preset buttons. I do agree that it appears a bit cluttered and also prevents any new preset options from being added on the same row. My only concern with a hiding it in a dialog would be that the ability to quickly iterate on new formulae could be slightly hindered by the few extra clicks. But this could probably be almost completely solved by providing a preview waveform and/or another piano input in the dialog.

**Comment by squiggythings** [comment]
For sure, I definitely think a preview waveform is necessary. Inheriting from the existing WaveModifyDialog should support this behavior to work as expected (the same way clicking "Smooth" allows you to preview the wave/sound before committing to it.) Although it might need some custom resizing to fit a longer expression text box.

**Comment by Dannode36** [comment]
I think I've finally settled on a direction for this PR. Without removing the current integration of the maths parser from the wave editor, I will implement an additional instrument to allow for real time modifications to a math expression through parameters and envelopes. 

To do this I'll need to slightly modify how expressions are constructed and evaluated, making this parser similar to that of other expression parsing libraries. The current architecture just isn't flexible enough but luckily still young in development. I'd also like to take this as an opportunity to "shine" up the code and also implement boolean operators.

**Comment by Dannode36** [comment]
Trying to write a custom parser was pretty fun lmao but NCalc is just so much more impressive. Hope the extra dependency is okay

**Comment by squiggythings** [comment]
I think making another instrument type is beyond the scope of what I would want wavetracker to be, especially for something as niche as real-time math expression synthesis. It's certainly cool (and would make a really neat VST imo!) but I feel it strays from the existing design paradigm that wave synthesis always happens from the wave bank, and sort of shifts the flavor of the tracker having math instruments be front and center alongside everything else.
I always would rather make existing features more powerful than adding new ones alongside them, so that new users can still get the hang of the program quicker and aren't as easily overwhelmed by a bunch of options. So I would probably only merge the extra wave editor functionality and not the whole new instrument, just as a heads up.

**Comment by Dannode36** [comment]
I see what you mean. I definitely did have trouble trying architect a new instrument because of how different it was to WaveTrackers existing paradigm. Especially:
> wave synthesis always happens from the wave bank

I think I just loved the real-time aspect of it a little too much...
It was pretty fun to implement at least lol. Btw this is actually the first opensource project I've ever contributed to, so I massively appreciate the support and open sourcing of the whole thing!

After looking at the commit history for this branch, I think what I'll do now is close this PR as out-of-scope or something and create a new (much cleaner) one with only the wave editor changes!
And just for clarification, this new PR would still utilise NCalc unless you'd prefer an "in-house" solution

**Comment by Dannode36** [comment]
Math expression instrument was out of scope. Moving changes over to #60

**Pull request closed without merging**
